name: download
on:
  schedule:
    - cron: '0 10 * * 1'
    
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Removing Chrome and Chromium, Installing new Chromium, Installing requirements.txt
        run: |
          sudo apt purge google-chrome-stable
          sudo apt purge chromium-browser
          sudo apt install -y chromium-browser
          pip install -r requirements.txt
      - name: Downloading pdf
        run: python ./headless/chromium-headless.py
      - name: Upload leaflet
        uses: actions/upload-artifact@v3
        with:
          name: angebote-tegut
          path: ./*.pdf